name: eco_wize
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  flutter_local_notifications: ^18.0.1
  firebase_auth_web: ^5.13.6
  provider: ^6.0.0  # تأكد من استخدام أحدث إصدار
  http: ^1.2.2
  dart_openai: ^5.1.0
  webview_flutter: ^4.2.2
  url_launcher: ^6.1.7
  flutter_usb_serial: ^0.0.2
  usb_serial: ^0.3.0
  firebase_database: ^11.3.1
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  timezone: ^0.10.0
  intl: ^0.19.0  # Check for the latest version
  location: ^4.4.0

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logoo.png"  # ضع مسار الشعار الجديد هنا

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logoo.png
  # - assets/images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: font
      fonts:
        - asset: assets/font/times-new-roman-ce.ttf
        - asset: assets/font/alfont_com_AlFont_com_arial.ttf
        - asset: assets/font/Roboto-Bold.ttf
        - asset: assets/font/OpenSans-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package